server:
    port: 8081
    tomcat:
      uri-encoding: utf-8
logging:
    file: ./inner-test.log
#  level:
#      com.inner.api: debug
spring:
    datasource:
        url: jdbc:mysql://xx.xx.xx.xx:3306/inner-system?useUnicode=true&characterEncoding=utf-8
        username: xxx
        password: xxxxx
        driver-class-name: com.mysql.jdbc.Driver
    dubbo:
            application:
              name: provider
            registry:
              address: zookeeper://127.0.0.1:2161
            protocol:
              name: dubbo
              port: 20880
              status : server
            scan: com.inner.api         provider:
              timeout: 300000
    data:
        solr:
          host: http://47.98.155.173:8983/solr